### PR TITLE
test translation

### PR DESCRIPTION
**Pull request by raynamharris**
This is the first time I've ever attempted to edit the underlying code of an image rather than using a tool like Illustrator... 🤞 it works

### CODE REVIEW

**Comment by raynamharris** [comment]
I don't think it worked :(

**Comment by pachamaltese** [comment]
@raynamharris Hi! what are you trying to edit exactly?

**Comment by raynamharris** [comment]
I'd like this to be in Spanish
screen shot 2019-01-19 at 3 54 19 pm

**Comment by pachamaltese** [comment]
@raynamharris if you want to replace texts, then edit https://github.com/pachamaltese/r4ds/blob/traduccion/diagrams/data-science-model.svg that is the fully editable version while the `-otp.svg` is a copy-paste safe version

**Comment by pachamaltese** [comment]
also @raynamharris the magic of Inkscape is that you can edit the underlying code :)

**Comment by raynamharris** [comment]
Ah, okay. Thanks! I'll test that out another day. We are wrapping up our hack session now. Thanks for your help!

**Pull request closed without merging**
